import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Breadcrumbs } from '@/_widgets/breadcrumbs';
import { Navbar } from '@/_widgets/navbar';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <Navbar />
                <main className="container mx-auto px-4">
                    <Breadcrumbs />
                    <div className="mt-2 md:mt-4">{children}</div>
                </main>
            </body>
        </html>
    );
}
